version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Amazon-clone-site

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: ubuntu
