version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      runas: root
  AfterInstall:
    - location: scripts/restart_server.sh
      runas: root
