version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Only if needed, remove if not using Node.js
  build:
    commands:
      - echo "Nothing to build for static site"
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
